<?php
/**
* Soap client Logmein
*
* Autogenerated with the Yii extension wsdl2php.
*/


class login
{
public $sEmail; //string;
public $sPassword; //string;
}

class loginResponse
{
public $loginResult; //loginRet;
}

class logout
{
}

class logoutResponse
{
public $logoutResult; //logoutRet;
}

class getAccount
{
public $sAuthCode; //string;
}

class getAccountResponse
{
public $getAccountResult; //getAccountRet;
public $iAccountID; //int;
public $sOrganization; //string;
public $iAdminID; //int;
public $iTechID; //int;
public $sEmail; //string;
}

class getHierarchy
{
public $sAuthCode; //string;
public $isNode; //boolean;
public $iNodeID; //int;
}

class getHierarchyResponse
{
public $getHierarchyResult; //getHierarchyRet;
public $aHierarchy; //ArrayOfHIERARCHY;
}

class ArrayOfHIERARCHY
{
public $HIERARCHY; //HIERARCHY;
}

class HIERARCHY
{
public $iNodeID; //int;
public $iParentID; //int;
public $sEmail; //string;
public $sName; //string;
public $sDescription; //string;
public $eStatus; //NODE_STATUS;
public $eType; //NODE_TYPE;
}

class getHierarchy_v2
{
public $sAuthCode; //string;
public $isNode; //boolean;
public $iNodeID; //int;
public $filterOutOfflineTech; //boolean;
}

class getHierarchy_v2Response
{
public $getHierarchy_v2Result; //getHierarchyRet;
public $aHierarchy; //ArrayOfHIERARCHY;
}

class assignChannel
{
public $iEntryID; //int;
public $iNodeID; //int;
public $sAuthCode; //string;
}

class assignChannelResponse
{
public $assignChannelResult; //assignChannelRet;
}

class unassignChannel
{
public $iEntryID; //int;
public $iNodeID; //int;
public $sAuthCode; //string;
}

class unassignChannelResponse
{
public $unassignChannelResult; //unassignChannelRet;
}

class createUser
{
public $iParentID; //int;
public $sAuthCode; //string;
}

class createUserResponse
{
public $createUserResult; //createUserRet;
public $iNewNodeID; //int;
}

class createGroup
{
public $iParentID; //int;
public $sAuthCode; //string;
}

class createGroupResponse
{
public $createGroupResult; //createGroupRet;
public $iNewNodeID; //int;
}

class deleteNode
{
public $iNodeID; //int;
public $sAuthCode; //string;
}

class deleteNodeResponse
{
public $deleteNodeResult; //deleteNodeRet;
}

class moveNode
{
public $iTargetNodeID; //int;
public $iNodeID; //int;
public $sAuthCode; //string;
}

class moveNodeResponse
{
public $moveNodeResult; //moveNodeRet;
}

class setUser
{
public $iNodeID; //int;
public $sName; //string;
public $sNick; //string;
public $sEmail; //string;
public $sSSOID; //string;
public $sPwd; //string;
public $sConfPwd; //string;
public $sCurrentPwd; //string;
public $eStatus; //nodeStatus;
public $sDescription; //string;
public $eAddOns; //hasMobileAddon;
public $sAuthCode; //string;
}

class setUserResponse
{
public $setUserResult; //setUserRet;
}

class setUser_v2
{
public $iNodeID; //int;
public $sName; //string;
public $sNick; //string;
public $sEmail; //string;
public $sSSOID; //string;
public $sPwd; //string;
public $sConfPwd; //string;
public $sCurrentPwd; //string;
public $eStatus; //nodeStatus;
public $sDescription; //string;
public $eAddOns; //hasMobileAddon;
public $bHasRPATAddOn; //boolean;
public $sAuthCode; //string;
}

class setUser_v2Response
{
public $setUser_v2Result; //setUserRet_v2;
}

class createUsers
{
public $users; //ArrayOfUSERDATA;
public $sAuthCode; //string;
}

class ArrayOfUSERDATA
{
public $USERDATA; //USERDATA;
}

class USERDATA
{
public $iUniqueId; //int;
public $iParentID; //int;
public $sName; //string;
public $sNick; //string;
public $sEmail; //string;
public $sSSOID; //string;
public $sPwd; //string;
public $sConfPwd; //string;
public $eStatus; //nodeStatus;
public $sDescription; //string;
public $eAddOns; //hasMobileAddon;
}

class createUsersResponse
{
public $createUsersResult; //CREATEUSERSINFO;
}

class CREATEUSERSINFO
{
public $createUserInfos; //ArrayOfCREATEUSERINFO;
public $state; //createUsersRet;
}

class ArrayOfCREATEUSERINFO
{
public $CREATEUSERINFO; //CREATEUSERINFO;
}

class CREATEUSERINFO
{
public $iNodeId; //int;
public $iUniqueId; //int;
public $userState; //createUsersRet;
}

class setUserStatus_v7_1
{
public $iNodeID; //int;
public $eStatus; //nodeStatus;
public $sAuthCode; //string;
}

class setUserStatus_v7_1Response
{
public $setUserStatus_v7_1Result; //setUserStatusRet_v7_1;
}

class setGroup_v2
{
public $iNodeID; //int;
public $sName; //string;
public $eStatus; //nodeStatus;
public $sDescription; //string;
public $aPermission; //ArrayOfNODE_PERMISSIONS_V2;
public $aLockedPermission; //ArrayOfNODE_PERMISSIONS_V2;
public $iStandardConcurrentLimit; //int;
public $iMobileConcurrentLimit; //int;
public $iRPATConcurrentLimit; //int;
public $sAuthCode; //string;
}

class ArrayOfNODE_PERMISSIONS_V2
{
public $NODE_PERMISSIONS_V2; //NODE_PERMISSIONS_V2;
}

class setGroup_v2Response
{
public $setGroup_v2Result; //setGroupRet_v2;
}

class setGroup
{
public $iNodeID; //int;
public $sName; //string;
public $eStatus; //nodeStatus;
public $sDescription; //string;
public $aPermission; //ArrayOfNODE_PERMISSIONS;
public $aLockedPermission; //ArrayOfNODE_PERMISSIONS;
public $iStandardConcurrentLimit; //int;
public $iMobileConcurrentLimit; //int;
public $sAuthCode; //string;
}

class ArrayOfNODE_PERMISSIONS
{
public $NODE_PERMISSIONS; //NODE_PERMISSIONS;
}

class setGroupResponse
{
public $setGroupResult; //setGroupRet;
}

class getUser
{
public $iNodeID; //int;
public $sAuthCode; //string;
}

class getUserResponse
{
public $getUserResult; //getUserRet;
public $oUser; //User;
}

class UserLogmein
{
public $iNodeID; //int;
public $sName; //string;
public $sNick; //string;
public $sEmail; //string;
public $sSSOID; //string;
public $sDescription; //string;
public $eType; //NODE_TYPE;
public $bAccountHolder; //boolean;
public $hasMobileAddon; //boolean;
public $eStatus; //NODE_STATUS;
}

class getUser_v2
{
public $iNodeID; //int;
public $sAuthCode; //string;
}

class getUser_v2Response
{
public $getUser_v2Result; //getUserRet;
public $oUser; //User_V2;
}

class User_V2
{
public $iNodeID; //int;
public $sName; //string;
public $sNick; //string;
public $sEmail; //string;
public $sSSOID; //string;
public $sDescription; //string;
public $eType; //NODE_TYPE;
public $bAccountHolder; //boolean;
public $hasMobileAddon; //boolean;
public $hasRPATAddon; //boolean;
public $eStatus; //NODE_STATUS;
}

class getUser_v3
{
public $iNodeID; //int;
public $sUserEmail; //string;
public $sAuthCode; //string;
}

class getUser_v3Response
{
public $getUser_v3Result; //getUserRet_v2;
public $oUser; //User_V2;
}

class getGroup_v2
{
public $iNodeID; //int;
public $sAuthCode; //string;
}

class getGroup_v2Response
{
public $getGroup_v2Result; //getGroupRet;
public $oGroup; //Group_V2;
}

class Group_V2
{
public $iNodeID; //int;
public $sName; //string;
public $sDescription; //string;
public $eType; //NODE_TYPE;
public $aPermissions; //ArrayOfNODE_PERMISSIONS_V2;
public $aLockedPermissions; //ArrayOfNODE_PERMISSIONS_V2;
public $isEnabled; //boolean;
public $iStandardConcurrentLimit; //int;
public $iMobileConcurrentLimit; //int;
public $iRPATConcurrentLimit; //int;
}

class getGroup
{
public $iNodeID; //int;
public $sAuthCode; //string;
}

class getGroupResponse
{
public $getGroupResult; //getGroupRet;
public $oGroup; //Group;
}

class Group
{
public $iNodeID; //int;
public $sName; //string;
public $sDescription; //string;
public $eType; //NODE_TYPE;
public $aPermissions; //ArrayOfNODE_PERMISSIONS;
public $aLockedPermissions; //ArrayOfNODE_PERMISSIONS;
public $isEnabled; //boolean;
public $iStandardConcurrentLimit; //int;
public $iMobileConcurrentLimit; //int;
}

class getSession_V3
{
public $iNodeID; //int;
public $eNodeRef; //NODE_REF;
public $sAuthCode; //string;
}

class getSession_V3Response
{
public $getSession_V3Result; //getSessionRet;
public $aSessions; //ArrayOfSESSION_V3;
}

class ArrayOfSESSION_V3
{
public $SESSION_V3; //SESSION_V3;
}

class SESSION_V3
{
public $iID; //int;
public $bStatus; //SESSION_STATUS_V3;
public $sStatus; //string;
public $iEntry; //int;
public $sEntry; //string;
public $iTechnician; //int;
public $sTechnician; //string;
public $sStartTime; //string;
public $iWaitingTimeInSec; //int;
public $sCustomField0; //string;
public $sCustomField1; //string;
public $sCustomField2; //string;
public $sCustomField3; //string;
public $sCustomField4; //string;
public $sCustomField5; //string;
public $sLanguage; //string;
public $sTransferredTo; //string;
public $sTransferredComment; //string;
public $bIsLead; //boolean;
public $bHandingOff; //boolean;
}

class getSession_V2
{
public $iNodeID; //int;
public $eNodeRef; //NODE_REF;
public $sAuthCode; //string;
}

class getSession_V2Response
{
public $getSession_V2Result; //getSessionRet;
public $aSessions; //ArrayOfSESSION_V2;
}

class ArrayOfSESSION_V2
{
public $SESSION_V2; //SESSION_V2;
}

class SESSION_V2
{
public $iID; //int;
public $bStatus; //STATUS;
public $sStatus; //string;
public $iEntry; //int;
public $sEntry; //string;
public $iTechnician; //int;
public $sTechnician; //string;
public $sStartTime; //string;
public $iWaitingTimeInSec; //int;
public $sCustomField0; //string;
public $sCustomField1; //string;
public $sCustomField2; //string;
public $sLanguage; //string;
public $sTransferredTo; //string;
public $sTransferredComment; //string;
public $bIsLead; //boolean;
public $bHandingOff; //boolean;
}

class getSession
{
public $iNodeID; //int;
public $eNodeRef; //NODE_REF;
public $sAuthCode; //string;
}

class getSessionResponse
{
public $getSessionResult; //getSessionRet;
public $aSessions; //ArrayOfSESSION;
}

class ArrayOfSESSION
{
public $SESSION; //SESSION;
}

class SESSION
{
public $iID; //int;
public $bStatus; //STATUS;
public $sStatus; //string;
public $iEntry; //int;
public $sEntry; //string;
public $iTechnician; //int;
public $sTechnician; //string;
public $sStartTime; //string;
public $iWaitingTimeInSec; //int;
public $sCustomField0; //string;
public $sCustomField1; //string;
public $sCustomField2; //string;
public $sLanguage; //string;
public $sTransferredTo; //string;
public $sTransferredComment; //string;
}

class getReport
{
public $iNodeID; //int;
public $eNodeRef; //NODE_REF;
public $sAuthCode; //string;
}

class getReportResponse
{
public $getReportResult; //getReportRet;
public $sReport; //string;
}

class getReport_v2
{
public $iNodeID; //int;
public $eNodeRef; //NODE_REF_V2;
public $sAuthCode; //string;
}

class getReport_v2Response
{
public $getReport_v2Result; //getReportRet;
public $sReport; //string;
}

class getChat
{
public $iSessionID; //int;
public $sAuthCode; //string;
}

class getChatResponse
{
public $getChatResult; //getChatRet;
public $sChatLog; //string;
}

class getNote
{
public $iSessionID; //int;
public $sAuthCode; //string;
}

class getNoteResponse
{
public $getNoteResult; //getNoteRet;
public $sNote; //string;
}

class getReportArea
{
public $sAuthCode; //string;
}

class getReportAreaResponse
{
public $getReportAreaResult; //getReportAreaRet;
public $eReportArea; //REPORT;
}

class getReportArea_v2
{
public $sAuthCode; //string;
}

class getReportArea_v2Response
{
public $getReportArea_v2Result; //getReportAreaRet;
public $eReportArea; //REPORT_V2;
}

class setReportArea
{
public $eReportArea; //REPORT;
public $sAuthCode; //string;
}

class setReportAreaResponse
{
public $setReportAreaResult; //setReportAreaRet;
}

class setReportArea_v2
{
public $eReportArea; //REPORT_V2;
public $sAuthCode; //string;
}

class setReportArea_v2Response
{
public $setReportArea_v2Result; //setReportAreaRet;
}

class getDelimiter
{
public $sAuthCode; //string;
}

class getDelimiterResponse
{
public $getDelimiterResult; //getDelimiterRet;
public $sDelimiter; //string;
}

class setDelimiter
{
public $sDelimiter; //string;
public $sAuthCode; //string;
}

class setDelimiterResponse
{
public $setDelimiterResult; //setDelimiterRet;
}

class getOutput
{
public $sAuthCode; //string;
}

class getOutputResponse
{
public $getOutputResult; //getOutputRet;
public $eOutput; //OUTPUT;
}

class setOutput
{
public $eOutput; //OUTPUT;
public $sAuthCode; //string;
}

class setOutputResponse
{
public $setOutputResult; //setOutputRet;
}

class getReportDate
{
public $sAuthCode; //string;
}

class getReportDateResponse
{
public $getReportDateResult; //getReportDateRet;
public $sBeginDate; //string;
public $sEndDate; //string;
}

class getReportDate_v2
{
public $sAuthCode; //string;
}

class getReportDate_v2Response
{
public $getReportDate_v2Result; //getReportDateRet;
public $dBeginDate; //dateTime;
public $dEndDate; //dateTime;
}

class setReportDate
{
public $sBeginDate; //string;
public $sEndDate; //string;
public $sAuthCode; //string;
}

class setReportDateResponse
{
public $setReportDateResult; //setReportDateRet;
}

class setReportDate_v2
{
public $dBeginDate; //dateTime;
public $dEndDate; //dateTime;
public $sAuthCode; //string;
}

class setReportDate_v2Response
{
public $setReportDate_v2Result; //setReportDateRet;
}

class getReportTime
{
public $sAuthCode; //string;
}

class getReportTimeResponse
{
public $getReportTimeResult; //getReportTimeRet;
public $sBeginTime; //string;
public $sEndTime; //string;
}

class setReportTime
{
public $sBeginTime; //string;
public $sEndTime; //string;
public $sAuthCode; //string;
}

class setReportTimeResponse
{
public $setReportTimeResult; //setReportTimeRet;
}

class getTimezone
{
public $sAuthCode; //string;
}

class getTimezoneResponse
{
public $getTimezoneResult; //getTimezoneRet;
public $sTimezone; //short;
}

class setTimezone
{
public $sTimezone; //short;
public $sAuthCode; //string;
}

class setTimezoneResponse
{
public $setTimezoneResult; //setTimezoneRet;
}

class getDateFormat
{
public $sAuthCode; //string;
}

class getDateFormatResponse
{
public $getDateFormatResult; //getDateFormatRet;
public $eDateFormat; //DATEFORMAT;
}

class setDateFormat
{
public $eDateFormat; //DATEFORMAT;
public $sAuthCode; //string;
}

class setDateFormatResponse
{
public $setDateFormatResult; //setDateFormatRet;
}

class requestAuthCode
{
public $sEmail; //string;
public $sPassword; //string;
}

class requestAuthCodeResponse
{
public $requestAuthCodeResult; //requestAuthCodeRet;
public $sAuthCode; //string;
}

class requestAuthCodeSSO
{
public $sSSOID; //string;
public $sPassword; //string;
public $iCompanyID; //int;
}

class requestAuthCodeSSOResponse
{
public $requestAuthCodeSSOResult; //requestAuthCodeSSORet;
public $sAuthCode; //string;
}

class requestPINCode
{
public $sCField0; //string;
public $sCField1; //string;
public $sCField2; //string;
public $sCField3; //string;
public $sCField4; //string;
public $sCField5; //string;
public $sTracking0; //string;
public $bNoTechConsole; //boolean;
public $sAuthCode; //string;
}

class requestPINCodeResponse
{
public $requestPINCodeResult; //requestPINCodeRet;
public $iPINCode; //int;
}

class generateEmailText
{
public $iPINCode; //int;
public $sAuthCode; //string;
}

class generateEmailTextResponse
{
public $generateEmailTextResult; //generateEmailTextRet;
public $sSubject; //string;
public $sText; //string;
public $sLink; //string;
public $sSignature; //string;
}

class startSession
{
public $iSession; //int;
public $iNode; //int;
public $sAuthCode; //string;
}

class startSessionResponse
{
public $startSessionResult; //startSessionRet;
}

class holdSession
{
public $iSession; //int;
public $sAuthCode; //string;
}

class holdSessionResponse
{
public $holdSessionResult; //holdSessionRet;
}

class transferSession
{
public $iSession; //int;
public $iNode; //int;
public $eNodeRef; //NODE_REF;
public $sComment; //string;
public $sAuthCode; //string;
}

class transferSessionResponse
{
public $transferSessionResult; //transferSessionRet;
}

class closeSession
{
public $iSession; //int;
public $sAuthCode; //string;
}

class closeSessionResponse
{
public $closeSessionResult; //closeSessionRet;
}

class cancelAction
{
public $iSession; //int;
public $sAuthCode; //string;
}

class cancelActionResponse
{
public $cancelActionResult; //cancelActionRet;
}

class isAnyTechAvailableOnChannel
{
public $iChannelID; //int;
public $bExcludingAwayAndBusy; //boolean;
}

class isAnyTechAvailableOnChannelResponse
{
public $isAnyTechAvailableOnChannelResult; //isAnyTechAvailableOnChannelRet;
public $bHasOnlineTechnicians; //boolean;
}

/**
* The soap client proxy class
*/
//class Logmein extends LogmeinBase 
class Logmein
 {
	public $soapClient;

	private static $classmap = array(
		'login'=>'login',
		'loginResponse'=>'loginResponse',
		'logout'=>'logout',
		'logoutResponse'=>'logoutResponse',
		'getAccount'=>'getAccount',
		'getAccountResponse'=>'getAccountResponse',
		'getHierarchy'=>'getHierarchy',
		'getHierarchyResponse'=>'getHierarchyResponse',
		'ArrayOfHIERARCHY'=>'ArrayOfHIERARCHY',
		'HIERARCHY'=>'HIERARCHY',
		'getHierarchy_v2'=>'getHierarchy_v2',
		'getHierarchy_v2Response'=>'getHierarchy_v2Response',
		'assignChannel'=>'assignChannel',
		'assignChannelResponse'=>'assignChannelResponse',
		'unassignChannel'=>'unassignChannel',
		'unassignChannelResponse'=>'unassignChannelResponse',
		'createUser'=>'createUser',
		'createUserResponse'=>'createUserResponse',
		'createGroup'=>'createGroup',
		'createGroupResponse'=>'createGroupResponse',
		'deleteNode'=>'deleteNode',
		'deleteNodeResponse'=>'deleteNodeResponse',
		'moveNode'=>'moveNode',
		'moveNodeResponse'=>'moveNodeResponse',
		'setUser'=>'setUser',
		'setUserResponse'=>'setUserResponse',
		'setUser_v2'=>'setUser_v2',
		'setUser_v2Response'=>'setUser_v2Response',
		'createUsers'=>'createUsers',
		'ArrayOfUSERDATA'=>'ArrayOfUSERDATA',
		'USERDATA'=>'USERDATA',
		'createUsersResponse'=>'createUsersResponse',
		'CREATEUSERSINFO'=>'CREATEUSERSINFO',
		'ArrayOfCREATEUSERINFO'=>'ArrayOfCREATEUSERINFO',
		'CREATEUSERINFO'=>'CREATEUSERINFO',
		'setUserStatus_v7_1'=>'setUserStatus_v7_1',
		'setUserStatus_v7_1Response'=>'setUserStatus_v7_1Response',
		'setGroup_v2'=>'setGroup_v2',
		'ArrayOfNODE_PERMISSIONS_V2'=>'ArrayOfNODE_PERMISSIONS_V2',
		'setGroup_v2Response'=>'setGroup_v2Response',
		'setGroup'=>'setGroup',
		'ArrayOfNODE_PERMISSIONS'=>'ArrayOfNODE_PERMISSIONS',
		'setGroupResponse'=>'setGroupResponse',
		'getUser'=>'getUser',
		'getUserResponse'=>'getUserResponse',
		'User'=>'User',
		'getUser_v2'=>'getUser_v2',
		'getUser_v2Response'=>'getUser_v2Response',
		'User_V2'=>'User_V2',
		'getUser_v3'=>'getUser_v3',
		'getUser_v3Response'=>'getUser_v3Response',
		'getGroup_v2'=>'getGroup_v2',
		'getGroup_v2Response'=>'getGroup_v2Response',
		'Group_V2'=>'Group_V2',
		'getGroup'=>'getGroup',
		'getGroupResponse'=>'getGroupResponse',
		'Group'=>'Group',
		'getSession_V3'=>'getSession_V3',
		'getSession_V3Response'=>'getSession_V3Response',
		'ArrayOfSESSION_V3'=>'ArrayOfSESSION_V3',
		'SESSION_V3'=>'SESSION_V3',
		'getSession_V2'=>'getSession_V2',
		'getSession_V2Response'=>'getSession_V2Response',
		'ArrayOfSESSION_V2'=>'ArrayOfSESSION_V2',
		'SESSION_V2'=>'SESSION_V2',
		'getSession'=>'getSession',
		'getSessionResponse'=>'getSessionResponse',
		'ArrayOfSESSION'=>'ArrayOfSESSION',
		'SESSION'=>'SESSION',
		'getReport'=>'getReport',
		'getReportResponse'=>'getReportResponse',
		'getReport_v2'=>'getReport_v2',
		'getReport_v2Response'=>'getReport_v2Response',
		'getChat'=>'getChat',
		'getChatResponse'=>'getChatResponse',
		'getNote'=>'getNote',
		'getNoteResponse'=>'getNoteResponse',
		'getReportArea'=>'getReportArea',
		'getReportAreaResponse'=>'getReportAreaResponse',
		'getReportArea_v2'=>'getReportArea_v2',
		'getReportArea_v2Response'=>'getReportArea_v2Response',
		'setReportArea'=>'setReportArea',
		'setReportAreaResponse'=>'setReportAreaResponse',
		'setReportArea_v2'=>'setReportArea_v2',
		'setReportArea_v2Response'=>'setReportArea_v2Response',
		'getDelimiter'=>'getDelimiter',
		'getDelimiterResponse'=>'getDelimiterResponse',
		'setDelimiter'=>'setDelimiter',
		'setDelimiterResponse'=>'setDelimiterResponse',
		'getOutput'=>'getOutput',
		'getOutputResponse'=>'getOutputResponse',
		'setOutput'=>'setOutput',
		'setOutputResponse'=>'setOutputResponse',
		'getReportDate'=>'getReportDate',
		'getReportDateResponse'=>'getReportDateResponse',
		'getReportDate_v2'=>'getReportDate_v2',
		'getReportDate_v2Response'=>'getReportDate_v2Response',
		'setReportDate'=>'setReportDate',
		'setReportDateResponse'=>'setReportDateResponse',
		'setReportDate_v2'=>'setReportDate_v2',
		'setReportDate_v2Response'=>'setReportDate_v2Response',
		'getReportTime'=>'getReportTime',
		'getReportTimeResponse'=>'getReportTimeResponse',
		'setReportTime'=>'setReportTime',
		'setReportTimeResponse'=>'setReportTimeResponse',
		'getTimezone'=>'getTimezone',
		'getTimezoneResponse'=>'getTimezoneResponse',
		'setTimezone'=>'setTimezone',
		'setTimezoneResponse'=>'setTimezoneResponse',
		'getDateFormat'=>'getDateFormat',
		'getDateFormatResponse'=>'getDateFormatResponse',
		'setDateFormat'=>'setDateFormat',
		'setDateFormatResponse'=>'setDateFormatResponse',
		'requestAuthCode'=>'requestAuthCode',
		'requestAuthCodeResponse'=>'requestAuthCodeResponse',
		'requestAuthCodeSSO'=>'requestAuthCodeSSO',
		'requestAuthCodeSSOResponse'=>'requestAuthCodeSSOResponse',
		'requestPINCode'=>'requestPINCode',
		'requestPINCodeResponse'=>'requestPINCodeResponse',
		'generateEmailText'=>'generateEmailText',
		'generateEmailTextResponse'=>'generateEmailTextResponse',
		'startSession'=>'startSession',
		'startSessionResponse'=>'startSessionResponse',
		'holdSession'=>'holdSession',
		'holdSessionResponse'=>'holdSessionResponse',
		'transferSession'=>'transferSession',
		'transferSessionResponse'=>'transferSessionResponse',
		'closeSession'=>'closeSession',
		'closeSessionResponse'=>'closeSessionResponse',
		'cancelAction'=>'cancelAction',
		'cancelActionResponse'=>'cancelActionResponse',
		'isAnyTechAvailableOnChannel'=>'isAnyTechAvailableOnChannel',
		'isAnyTechAvailableOnChannelResponse'=>'isAnyTechAvailableOnChannelResponse',

);

function __construct($url='https://secure.logmeinrescue.com/API/API.asmx?WSDL')
{
$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
}


function login($login)
{
	$loginResponse = $this->soapClient->login($login);
	return $loginResponse;
}

function logout($logout)
{
	$logoutResponse = $this->soapClient->logout($logout);
	return $logoutResponse;
}

function getAccount($getAccount)
{
	$getAccountResponse = $this->soapClient->getAccount($getAccount);
	return $getAccountResponse;
}

function getHierarchy($getHierarchy)
{
	$getHierarchyResponse = $this->soapClient->getHierarchy($getHierarchy);
	return $getHierarchyResponse;
}

function getHierarchy_v2($getHierarchy_v2)
{
	$getHierarchy_v2Response = $this->soapClient->getHierarchy_v2($getHierarchy_v2);
	return $getHierarchy_v2Response;
}

function assignChannel($assignChannel)
{
	$assignChannelResponse = $this->soapClient->assignChannel($assignChannel);
	return $assignChannelResponse;
}

function unassignChannel($unassignChannel)
{
	$unassignChannelResponse = $this->soapClient->unassignChannel($unassignChannel);
	return $unassignChannelResponse;
}

function createUser($createUser)
{
	$createUserResponse = $this->soapClient->createUser($createUser);
	return $createUserResponse;
}

function createGroup($createGroup)
{
	$createGroupResponse = $this->soapClient->createGroup($createGroup);
	return $createGroupResponse;
}

function deleteNode($deleteNode)
{
	$deleteNodeResponse = $this->soapClient->deleteNode($deleteNode);
	return $deleteNodeResponse;
}

function moveNode($moveNode)
{
	$moveNodeResponse = $this->soapClient->moveNode($moveNode);
	return $moveNodeResponse;
}

function setUser($setUser)
{
	$setUserResponse = $this->soapClient->setUser($setUser);
	return $setUserResponse;
}

function setUser_v2($setUser_v2)
{
	$setUser_v2Response = $this->soapClient->setUser_v2($setUser_v2);
	return $setUser_v2Response;
}

function createUsers($createUsers)
{
	$createUsersResponse = $this->soapClient->createUsers($createUsers);
	return $createUsersResponse;
}

function setUserStatus_v7_1($setUserStatus_v7_1)
{
	$setUserStatus_v7_1Response = $this->soapClient->setUserStatus_v7_1($setUserStatus_v7_1);
	return $setUserStatus_v7_1Response;
}

function setGroup_v2($setGroup_v2)
{
	$setGroup_v2Response = $this->soapClient->setGroup_v2($setGroup_v2);
	return $setGroup_v2Response;
}

function setGroup($setGroup)
{
	$setGroupResponse = $this->soapClient->setGroup($setGroup);
	return $setGroupResponse;
}

function getUser($getUser)
{
	$getUserResponse = $this->soapClient->getUser($getUser);
	return $getUserResponse;
}

function getUser_v2($getUser_v2)
{
	$getUser_v2Response = $this->soapClient->getUser_v2($getUser_v2);
	return $getUser_v2Response;
}

function getUser_v3($getUser_v3)
{
	$getUser_v3Response = $this->soapClient->getUser_v3($getUser_v3);
	return $getUser_v3Response;
}

function getGroup_v2($getGroup_v2)
{
	$getGroup_v2Response = $this->soapClient->getGroup_v2($getGroup_v2);
	return $getGroup_v2Response;
}

function getGroup($getGroup)
{
	$getGroupResponse = $this->soapClient->getGroup($getGroup);
	return $getGroupResponse;
}

function getSession_V3($getSession_V3)
{
	$getSession_V3Response = $this->soapClient->getSession_V3($getSession_V3);
	return $getSession_V3Response;
}

function getSession_V2($getSession_V2)
{
	$getSession_V2Response = $this->soapClient->getSession_V2($getSession_V2);
	return $getSession_V2Response;
}

function getSession($getSession)
{
	$getSessionResponse = $this->soapClient->getSession($getSession);
	return $getSessionResponse;
}

function getReport($getReport)
{
	$getReportResponse = $this->soapClient->getReport($getReport);
	return $getReportResponse;
}

function getReport_v2($getReport_v2)
{
	$getReport_v2Response = $this->soapClient->getReport_v2($getReport_v2);
	return $getReport_v2Response;
}

function getChat($getChat)
{
	$getChatResponse = $this->soapClient->getChat($getChat);
	return $getChatResponse;
}

function getNote($getNote)
{
	$getNoteResponse = $this->soapClient->getNote($getNote);
	return $getNoteResponse;
}

function getReportArea($getReportArea)
{
	$getReportAreaResponse = $this->soapClient->getReportArea($getReportArea);
	return $getReportAreaResponse;
}

function getReportArea_v2($getReportArea_v2)
{
	$getReportArea_v2Response = $this->soapClient->getReportArea_v2($getReportArea_v2);
	return $getReportArea_v2Response;
}

function setReportArea($setReportArea)
{
	$setReportAreaResponse = $this->soapClient->setReportArea($setReportArea);
	return $setReportAreaResponse;
}

function setReportArea_v2($setReportArea_v2)
{
	$setReportArea_v2Response = $this->soapClient->setReportArea_v2($setReportArea_v2);
	return $setReportArea_v2Response;
}

function getDelimiter($getDelimiter)
{
	$getDelimiterResponse = $this->soapClient->getDelimiter($getDelimiter);
	return $getDelimiterResponse;
}

function setDelimiter($setDelimiter)
{
	$setDelimiterResponse = $this->soapClient->setDelimiter($setDelimiter);
	return $setDelimiterResponse;
}

function getOutput($getOutput)
{
	$getOutputResponse = $this->soapClient->getOutput($getOutput);
	return $getOutputResponse;
}

function setOutput($setOutput)
{
	$setOutputResponse = $this->soapClient->setOutput($setOutput);
	return $setOutputResponse;
}

function getReportDate($getReportDate)
{
	$getReportDateResponse = $this->soapClient->getReportDate($getReportDate);
	return $getReportDateResponse;
}

function getReportDate_v2($getReportDate_v2)
{
	$getReportDate_v2Response = $this->soapClient->getReportDate_v2($getReportDate_v2);
	return $getReportDate_v2Response;
}

function setReportDate($setReportDate)
{
	$setReportDateResponse = $this->soapClient->setReportDate($setReportDate);
	return $setReportDateResponse;
}

function setReportDate_v2($setReportDate_v2)
{
	$setReportDate_v2Response = $this->soapClient->setReportDate_v2($setReportDate_v2);
	return $setReportDate_v2Response;
}

function getReportTime($getReportTime)
{
	$getReportTimeResponse = $this->soapClient->getReportTime($getReportTime);
	return $getReportTimeResponse;
}

function setReportTime($setReportTime)
{
	$setReportTimeResponse = $this->soapClient->setReportTime($setReportTime);
	return $setReportTimeResponse;
}

function getTimezone($getTimezone)
{
	$getTimezoneResponse = $this->soapClient->getTimezone($getTimezone);
	return $getTimezoneResponse;
}

function setTimezone($setTimezone)
{
	$setTimezoneResponse = $this->soapClient->setTimezone($setTimezone);
	return $setTimezoneResponse;
}

function getDateFormat($getDateFormat)
{
	$getDateFormatResponse = $this->soapClient->getDateFormat($getDateFormat);
	return $getDateFormatResponse;
}

function setDateFormat($setDateFormat)
{
	$setDateFormatResponse = $this->soapClient->setDateFormat($setDateFormat);
	return $setDateFormatResponse;
}

function requestAuthCode($requestAuthCode)
{
	$requestAuthCodeResponse = $this->soapClient->requestAuthCode($requestAuthCode);
	return $requestAuthCodeResponse;
}

function requestAuthCodeSSO($requestAuthCodeSSO)
{
	$requestAuthCodeSSOResponse = $this->soapClient->requestAuthCodeSSO($requestAuthCodeSSO);
	return $requestAuthCodeSSOResponse;
}

function requestPINCode($requestPINCode)
{
	$requestPINCodeResponse = $this->soapClient->requestPINCode($requestPINCode);
	return $requestPINCodeResponse;
}

function generateEmailText($generateEmailText)
{
	$generateEmailTextResponse = $this->soapClient->generateEmailText($generateEmailText);
	return $generateEmailTextResponse;
}

function startSession($startSession)
{
	$startSessionResponse = $this->soapClient->startSession($startSession);
	return $startSessionResponse;
}

function holdSession($holdSession)
{
	$holdSessionResponse = $this->soapClient->holdSession($holdSession);
	return $holdSessionResponse;
}

function transferSession($transferSession)
{
	$transferSessionResponse = $this->soapClient->transferSession($transferSession);
	return $transferSessionResponse;
}

function closeSession($closeSession)
{
	$closeSessionResponse = $this->soapClient->closeSession($closeSession);
	return $closeSessionResponse;
}

function cancelAction($cancelAction)
{
	$cancelActionResponse = $this->soapClient->cancelAction($cancelAction);
	return $cancelActionResponse;
}

function isAnyTechAvailableOnChannel($isAnyTechAvailableOnChannel)
{
	$isAnyTechAvailableOnChannelResponse = $this->soapClient->isAnyTechAvailableOnChannel($isAnyTechAvailableOnChannel);
	return $isAnyTechAvailableOnChannelResponse;
}
}
  


